volumes:
  dosasm_db_data:
  dosasm_prometheus:
  dosasm_grafana:

networks:
  dosasm_net:
    name: dosasm_net

services:
  dosasm:
    user: ${USER}
    image: "dosassembly"
    restart: always
    command:
      --config-file=/app/config/config.yaml
    env_file:
      - ".env_stage"
    volumes:
      - ./www/templates:/app/www/templates
      - ./config/dosasm:/app/config
      - ./sql:/app/migrations
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"
    depends_on:
      - postgres
    networks:
      - dosasm_net
  postgres:
    image: "postgres:14-alpine"
    restart: always
    ports:
      - "5444:5432"
    env_file:
      - ".env_stage"
    volumes:
      - ./docker-assets/postgresql/import:/tmp/import:ro
      - type: volume
        source: dosasm_db_data
        target: /var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"
    networks:
      - dosasm_net
  prometheus:
    image: "prom/prometheus"
    restart: always
    volumes:
      - ./docker-assets/stage/prometheus:/etc/prometheus
      - type: volume
        source: dosasm_prometheus
        target: /prometheus
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"
    networks:
      - dosasm_net
  grafana:
    hostname: dosasm-grafana # there can be multiple grafanas and nginx must be able to distinguish them
    image: "grafana/grafana-oss"
    restart: always
    volumes:
      - type: volume
        source: dosasm_grafana
        target: /var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"
    depends_on:
      - prometheus
    networks:
      - dosasm_net
