service:
  name: dosassembly
  prometheus:
    server:
      port: {{DOSASM_METRICS_PORT}}
    metrics:
      namespace: dosasm
  http:
    api_base: api
    port: {{DOSASM_API_PORT}}
  dbase:
    type: postgres
    conn_string: host={{DB_HOST}} port={{DB_PORT}} dbname={{DB_NAME}} user={{DB_USER}} password={{DB_PASSWORD}} sslmode=disable
    migrations: {{DB_MIGRATIONS}}
  playground_server: {{PLAYGROUND_SERVER}}
  playground_api_token: {{PLAYGROUND_TOKEN}}
  templates_path: {{TEMPLATES_PATH}}