app:
  http:
    port: {{DOSASM_API_PORT}}
    stats_port: {{DOSASM_METRICS_PORT}}
    metrics:
      namespace: dosasm
dosasm:
  api_base: api
  name: dosassembly
  dbase:
    type: postgres
    conn_string: host={{DB_HOST}} port={{DB_PORT}} dbname={{DB_NAME}} user={{DB_USER}} password={{DB_PASSWORD}} sslmode=disable
    migrations: {{DB_MIGRATIONS}}
  playground_server: {{PLAYGROUND_SERVER}}
  playground_api_token: {{PLAYGROUND_TOKEN}}
  templates_path: {{TEMPLATES_PATH}}
