# developer environment
global:
  scrape_interval: 30s
  evaluation_interval: 30s
scrape_configs:
 - job_name: 'prometheus'
   static_configs:
    - targets: ['127.0.0.1:9090']
 - job_name: 'backend'
   static_configs:
    - targets: ['host.docker.internal:8241']
